apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clube-xadrez-ingress
  namespace: api-students
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: api.dataiesb.com
    http:
      paths:
      - path: /xadrez/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: clube-xadrez-backend
            port:
              number: 80
