AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Clube de Xadrez Backend

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        TABLE_NAME: clube-xadrez-table
        TOPIC_ARN: !Ref ClubeXadrezTopic

Resources:
  ClubeXadrezTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: clube-xadrez-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  ClubeXadrezTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: clube-xadrez-topic

  ClubeXadrezApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type'"

  ClubeXadrezFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: clube-xadrez-api
      Handler: src/handler.lambda_handler
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ClubeXadrezTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ClubeXadrezTopic.TopicName
      Events:
        ProxyAll:
          Type: Api
          Properties:
            RestApiId: !Ref ClubeXadrezApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Value: !Sub "https://${ClubeXadrezApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
